# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fasthtml-test',
                'doc_host': 'https://ninjalabo.github.io',
                'git_url': 'https://github.com/ninjalabo/fasthtml-test',
                'lib_path': 'fasthtml_test'},
  'syms': { 'fasthtml_test.chatbot': { 'fasthtml_test.chatbot.ChatInput': ('chatbot.html#chatinput', 'fasthtml_test/chatbot.py'),
                                       'fasthtml_test.chatbot.ChatMessage': ('chatbot.html#chatmessage', 'fasthtml_test/chatbot.py'),
                                       'fasthtml_test.chatbot.index': ('chatbot.html#index', 'fasthtml_test/chatbot.py'),
                                       'fasthtml_test.chatbot.send': ('chatbot.html#send', 'fasthtml_test/chatbot.py')},
            'fasthtml_test.core': {'fasthtml_test.core.foo': ('core.html#foo', 'fasthtml_test/core.py')}}}
